export default {
  products: [
    {
      id: 321312,
      rasmlar: [
        "https://uy-bozor.uz/uploads/images/9241686547209.jpg",
        "https://uy-bozor.uz/uploads/images/17051686547209.jpg",
        "https://uy-bozor.uz/uploads/images/2711686547210.jpg",
        "https://uy-bozor.uz/uploads/images/12421686547210.jpg",
        "https://uy-bozor.uz/uploads/images/7531686547211.jpg",
        "https://uy-bozor.uz/uploads/images/18391686547211.jpg",
        "https://uy-bozor.uz/uploads/images/4581686547212.jpg",
      ],
      nomi: "Yangi qurilgan kvartira - sotiladi",
      price: 40000,
      shahar: "Farg'ona",
      tuman: "Rishton",
      manzil: "Yangi qurilgan uylar",
      xonalar: 3,
      yashashMaydon: 66,
      umumaiyMaydon: 88,
      uchstkaMaydon: 6,
      joylashuvi: "Shaharda",
      qavati: 4,
      shiftBalandligi: 3,
      mebel: false,
      uyHolati: "O'rtacha",
      qurilishTuri: "G'ishtli",
      uyTuri: "Uy",
      suv: "Uyda",
      elektr: true,
      isitish: "Markazlashgan, gazda",
      gaz: "Maagistral",
      sanuzel: "Hovlida",
      yili: "2018",
      mavjudNarsalar: "Koditsioner, ErTo'la, omborcha",
      yaqinidaJoylashgan: "Bollar bog'chasi",
      vositachilik: false,
      holati: "Yangi",
      malumot:
        "Продается квартира в центре себзара квартира 1 этаж / 4 комнаты 4х этажный дом.в квартире доступно старые мебели , двери и тд. Есть всякое удобство. Не требует ремонта.Если вам не нравится вы можете с легкостью отремонтировать) в квартире не жили студенты!",
    },
    {
      id: 4324112,
      rasmlar: [
        "https://uy-bozor.uz/uploads/images/20051694677316.jpg",
        "https://uy-bozor.uz/uploads/images/17151694677316.jpg",
        "https://uy-bozor.uz/uploads/images/6741694677317.jpg",
        "https://uy-bozor.uz/uploads/images/19511694677317.jpg",
        "https://uy-bozor.uz/uploads/images/5061694677317.jpg",
      ],
      nomi: "Ideal Jalyuzi dan ideal xizmatlar va takliflar!",
      price: 59000,
      shahar: "Toshkent",
      tuman: "Beshariq",
      manzil: "Yangi qurilgan uylar",
      xonalar: 5,
      yashashMaydon: 88,
      umumiyMaydon: 88,
      uchastkaMaydon: 6,
      joylashuvi: "Shaharda",
      qavati: 1,
      shiftBalandligi: 3,
      mebel: false,
      uyHolati: "O'rtacha",
      qurilishTuri: "G'ishtli",
      uyTuri: "Uy",
      suv: "Uyda",
      elektr: true,
      isitish: "Markazlashgan, gazda",
      gaz: "Maagistral",
      sanuzel: "Hovlida",
      yili: "2018",
      mavjudNarsalar: "Koditsioner, ErTo'la, omborcha",
      yaqinidaJoylashgan: "Bollar bog'chasi",
      vositachilik: false,
      holati: "Yangi",
      malumot:
        "Продается квартира в центре себзара квартира 1 этаж / 4 комнаты 4х этажный дом.в квартире доступно старые мебели , двери и тд. Есть всякое удобство. Не требует ремонта.Если вам не нравится вы можете с легкостью отремонтировать) в квартире не жили студенты!",
    },
    {
      id: 4321231,
      rasmlar: [
        "https://uy-bozor.uz/uploads/images/1551698992524.jpg",
        "https://uy-bozor.uz/uploads/images/4781698992524.jpg",
        "	https://uy-bozor.uz/uploads/images/4341698992524.jpg",
        "https://uy-bozor.uz/uploads/images/17171698992525.jpg",
        "	https://uy-bozor.uz/uploads/images/20001698992525.jpg",
      ],
      nomi: "Ideal Jalyuzi dan ideal xizmatlar va takliflar!",
      price: 45000,
      shahar: "Navoiy",
      tuman: "Buvayda",
      manzil: "Yangi qurilgan uylar",
      xonalar: 7,
      yashashMaydon: 88,
      umumiyMaydon: 88,
      uchastkaMaydon: 6,
      joylashuvi: "",
      qavati: 1,
      shiftBalandligi: 3,
      mebel: false,
      uyHolati: "",
      qurilishTuri: "",
      uyTuri: "",
      suv: "",
      elektr: true,
      isitish: "",
      gaz: "Maagistral",
      sanuzel: "Hovlida",
      yili: "2018",
      mavjudNarsalar: "",
      yaqinidaJoylashgan: "",
      vositachilik: false,
      holati: "Yangi",
      malumot:
        "Продается квартира в центре себзара квартира 1 этаж / 4 комнаты 4х этажный дом.в квартире доступно старые мебели , двери и тд. Есть всякое удобство. Не требует ремонта.Если вам не нравится вы можете с легкостью отремонтировать) в квартире не жили студенты!",
    },
    {
      id: 432112,
      rasmlar: [
        "https://uy-bozor.uz/uploads/images/14831697522491.jpg",
        "https://uy-bozor.uz/uploads/images/18911697522492.jpg",
        "https://uy-bozor.uz/uploads/images/18421697522492.jpg",
        "https://uy-bozor.uz/uploads/images/14191697522492.jpg",
        "https://uy-bozor.uz/uploads/images/9631697522492.jpg",
      ],
      nomi: "Ideal Jalyuzi dan ideal xizmatlar va takliflar!",
      price: 40000,
      shahar: "Namangan",
      tuman: "Buvayda",
      manzil: "Yangi qurilgan uylar",
      xonalar: 13,
      yashashMaydon: 88,
      umumiyMaydon: 88,
      uchastkaMaydon: 6,
      joylashuvi: "Shaharda",
      qavati: 1,
      shiftBalandligi: 3,
      mebel: false,
      uyHolati: "O'rtacha",
      qurilishTuri: "G'ishtli",
      uyTuri: "Uy",
      suv: "Uyda",
      elektr: true,
      isitish: "Markazlashgan, gazda",
      gaz: "Maagistral",
      sanuzel: "Hovlida",
      yili: "2018",
      mavjudNarsalar: "Koditsioner, ErTo'la, omborcha",
      yaqinidaJoylashgan: "Bollar bog'chasi",
      vositachilik: false,
      holati: "Yangi",
      malumot:
        "Продается квартира в центре себзара квартира 1 этаж / 4 комнаты 4х этажный дом.в квартире доступно старые мебели , двери и тд. Есть всякое удобство. Не требует ремонта.Если вам не нравится вы можете с легкостью отремонтировать) в квартире не жили студенты!",
    },
    {
      id: 3297653,
      rasmlar: [
        "https://uy-bozor.uz/uploads/images/6991698925228.jpg",
        "https://uy-bozor.uz/uploads/images/11001698925228.jpg",
        "https://uy-bozor.uz/uploads/images/14181698925229.jpg",
      ],
      nomi: "Ideal Jalyuzi dan ideal xizmatlar va takliflar!",
      price: 30000,
      shahar: "Marg'ilon",
      tuman: "Oltiariq",
      manzil: "Yangi qurilgan uylar",
      xonalar: 2,
      yashashMaydon: 88,
      umumiyMaydon: 88,
      uchastkaMaydon: 6,
      joylashuvi: "Shaharda",
      qavati: 1,
      shiftBalandligi: 3,
      mebel: false,
      uyHolati: "O'rtacha",
      qurilishTuri: "G'ishtli",
      uyTuri: "Uy",
      suv: "Uyda",
      elektr: true,
      isitish: "Markazlashgan, gazda",
      gaz: "Maagistral",
      sanuzel: "Hovlida",
      yili: "2018",
      mavjudNarsalar: "Koditsioner, ErTo'la, omborcha",
      yaqinidaJoylashgan: "Bollar bog'chasi",
      vositachilik: false,
      holati: "Yangi",
      malumot:
        "Продается квартира в центре себзара квартира 1 этаж / 4 комнаты 4х этажный дом.в квартире доступно старые мебели , двери и тд. Есть всякое удобство. Не требует ремонта.Если вам не нравится вы можете с легкостью отремонтировать) в квартире не жили студенты!",
    },
    {
      id: 432411,
      rasmlar: [
        "https://uy-bozor.uz/uploads/images/13661699953299.jpg",
        "https://uy-bozor.uz/uploads/images/8811699953299.jpg",
        "https://uy-bozor.uz/uploads/images/19861699953300.jpg",
        "https://uy-bozor.uz/uploads/images/4101699953300.jpg",
        "https://uy-bozor.uz/uploads/images/3601699953300.jpg",
        "	https://uy-bozor.uz/uploads/images/7571699953300.jpg",
      ],
      nomi: "Ideal Jalyuzi dan ideal xizmatlar va takliflar!",
      price: 17000,
      shahar: "Qashqadaryo",
      tuman: "Bag'dod",
      manzil: "Yangi qurilgan uylar",
      xonalar: 1,
      yashashMaydon: 88,
      umumiyMaydon: 88,
      uchastkaMaydon: 6,
      joylashuvi: "Shaharda",
      qavati: 1,
      shiftBalandligi: 3,
      mebel: false,
      uyHolati: "O'rtacha",
      qurilishTuri: "G'ishtli",
      uyTuri: "Uy",
      suv: "Uyda",
      elektr: true,
      isitish: "Markazlashgan, gazda",
      gaz: "Maagistral",
      sanuzel: "Hovlida",
      yili: "2018",
      mavjudNarsalar: "Koditsioner, ErTo'la, omborcha",
      yaqinidaJoylashgan: "Bollar bog'chasi",
      vositachilik: false,
      holati: "Yangi",
      malumot:
        "Продается квартира в центре себзара квартира 1 этаж / 4 комнаты 4х этажный дом.в квартире доступно старые мебели , двери и тд. Есть всякое удобство. Не требует ремонта.Если вам не нравится вы можете с легкостью отремонтировать) в квартире не жили студенты!",
    },
    {
      id: 241155,
      rasmlar: [
        "https://uy-bozor.uz/uploads/images/10161699592531.jpg",
        "https://uy-bozor.uz/uploads/images/19941699592531.jpg",
        "	https://uy-bozor.uz/uploads/images/4551699592532.jpg",
        "https://uy-bozor.uz/uploads/images/14191699958269.jpg",
        "	https://uy-bozor.uz/uploads/images/5291699592532.jpg",
        "	https://uy-bozor.uz/uploads/images/8811699592532.jpg",
        "https://uy-bozor.uz/uploads/images/8491699592533.jpg",
        "https://uy-bozor.uz/uploads/images/17591699592533.jpg",
        "https://uy-bozor.uz/uploads/images/10161699592531.jpg",
      ],
      nomi: "Ideal Jalyuzi dan ideal xizmatlar va takliflar!",
      price: 87000,
      shahar: "Toshkent",
      tuman: "Oltiariq",
      manzil: "Yangi qurilgan uylar",
      xonalar: 10,
      yashashMaydon: 88,
      umumiyMaydon: 88,
      uchastkaMaydon: 6,
      joylashuvi: "Shaharda",
      qavati: 1,
      shiftBalandligi: 3,
      mebel: false,
      uyHolati: "O'rtacha",
      qurilishTuri: "G'ishtli",
      uyTuri: "Uy",
      suv: "Uyda",
      elektr: true,
      isitish: "Markazlashgan, gazda",
      gaz: "Maagistral",
      sanuzel: "Hovlida",
      yili: "2018",
      mavjudNarsalar: "Koditsioner, ErTo'la, omborcha",
      yaqinidaJoylashgan: "Bollar bog'chasi",
      vositachilik: false,
      holati: "Yangi",
      malumot:
        "Продается квартира в центре себзара квартира 1 этаж / 4 комнаты 4х этажный дом.в квартире доступно старые мебели , двери и тд. Есть всякое удобство. Не требует ремонта.Если вам не нравится вы можете с легкостью отремонтировать) в квартире не жили студенты!",
    },
    {
      id: 426622,
      rasmlar: [
        "https://uy-bozor.uz/uploads/images/12041699351770.jpg",
        "https://uy-bozor.uz/uploads/images/9191699351770.jpg",
        "https://uy-bozor.uz/uploads/images/5041699351770.jpg",
      ],
      nomi: "Ideal Jalyuzi dan ideal xizmatlar va takliflar!",
      price: 15000,
      shahar: "Xorazm",
      tuman: "Dang'ara",
      manzil: "Yangi qurilgan uylar",
      xonalar: 1,
      yashashMaydon: 88,
      umumiyMaydon: 88,
      uchastkaMaydon: 6,
      joylashuvi: "Shaharda",
      qavati: 1,
      shiftBalandligi: 3,
      mebel: false,
      uyHolati: "O'rtacha",
      qurilishTuri: "G'ishtli",
      uyTuri: "Uy",
      suv: "Uyda",
      elektr: true,
      isitish: "Markazlashgan, gazda",
      gaz: "Maagistral",
      sanuzel: "Hovlida",
      yili: "2018",
      mavjudNarsalar: "Koditsioner, ErTo'la, omborcha",
      yaqinidaJoylashgan: "Bollar bog'chasi",
      vositachilik: false,
      holati: "Yangi",
      malumot:
        "Продается квартира в центре себзара квартира 1 этаж / 4 комнаты 4х этажный дом.в квартире доступно старые мебели , двери и тд. Есть всякое удобство. Не требует ремонта.Если вам не нравится вы можете с легкостью отремонтировать) в квартире не жили студенты!",
    },
    {
      id: 599323,
      rasmlar: [
        "https://uy-bozor.uz/uploads/images/16831697019924.jpg",
        "https://uy-bozor.uz/uploads/images/8991697019924.jpg",
        "	https://uy-bozor.uz/uploads/images/14641697019924.jpg",
        "https://uy-bozor.uz/uploads/images/3911697019925.jpg",
      ],
      nomi: "Ideal Jalyuzi dan ideal xizmatlar va takliflar!",
      price: 69000,
      shahar: "Qashqadaryo",
      tuman: "Furqat",
      manzil: "Yangi qurilgan uylar",
      xonalar: 7,
      yashashMaydon: 88,
      umumiyMaydon: 88,
      uchastkaMaydon: 6,
      joylashuvi: "Shaharda",
      qavati: 1,
      shiftBalandligi: 3,
      mebel: false,
      uyHolati: "O'rtacha",
      qurilishTuri: "G'ishtli",
      uyTuri: "Uy",
      suv: "Uyda",
      elektr: true,
      isitish: "Markazlashgan, gazda",
      gaz: "Maagistral",
      sanuzel: "Hovlida",
      yili: "2018",
      mavjudNarsalar: "Koditsioner, ErTo'la, omborcha",
      yaqinidaJoylashgan: "Bollar bog'chasi",
      vositachilik: false,
      holati: "Yangi",
      malumot:
        "Продается квартира в центре себзара квартира 1 этаж / 4 комнаты 4х этажный дом.в квартире доступно старые мебели , двери и тд. Есть всякое удобство. Не требует ремонта.Если вам не нравится вы можете с легкостью отремонтировать) в квартире не жили студенты!",
    },
    {
      id: 562803,
      rasmlar: [
        "https://uy-bozor.uz/uploads/images/3591698378115.jpg",
        "https://uy-bozor.uz/uploads/images/13351698378116.jpg",
        "	https://uy-bozor.uz/uploads/images/7101698378116.jpg",
        "https://uy-bozor.uz/uploads/images/14191699958269.jpg",
        "	https://uy-bozor.uz/uploads/images/2261698378116.jpg",
        "	https://uy-bozor.uz/uploads/images/16921698378116.jpg",
        "https://uy-bozor.uz/uploads/images/12591698378117.jpg",
        "	https://uy-bozor.uz/uploads/images/4321698378117.jpg",
      ],
      nomi: "Ideal Jalyuzi dan ideal xizmatlar va takliflar!",
      price: 38700,
      shahar: "Sirdaryo",
      tuman: "Qo'shtepa",
      manzil: "Yangi qurilgan uylar",
      xonalar: 11,
      yashashMaydon: 88,
      umumiyMaydon: 88,
      uchastkaMaydon: 6,
      joylashuvi: "Shaharda",
      qavati: 1,
      shiftBalandligi: 3,
      mebel: false,
      uyHolati: "O'rtacha",
      qurilishTuri: "G'ishtli",
      uyTuri: "Uy",
      suv: "Uyda",
      elektr: true,
      isitish: "Markazlashgan, gazda",
      gaz: "Maagistral",
      sanuzel: "Hovlida",
      yili: "2018",
      mavjudNarsalar: "Koditsioner, ErTo'la, omborcha",
      yaqinidaJoylashgan: "Bollar bog'chasi",
      vositachilik: false,
      holati: "Yangi",
      malumot:
        "Продается квартира в центре себзара квартира 1 этаж / 4 комнаты 4х этажный дом.в квартире доступно старые мебели , двери и тд. Есть всякое удобство. Не требует ремонта.Если вам не нравится вы можете с легкостью отремонтировать) в квартире не жили студенты!",
    },
    {
      id: 6555433,
      rasmlar: [
        "https://uy-bozor.uz/uploads/images/6991698925228.jpg",
        "https://uy-bozor.uz/uploads/images/11001698925228.jpg",
        "https://uy-bozor.uz/uploads/images/8601698925229.jpg",
        "https://uy-bozor.uz/uploads/images/14191699958269.jpg",
        "https://uy-bozor.uz/uploads/images/14181698925229.jpg",
        "	https://uy-bozor.uz/uploads/images/14591698925229.jpg",
        "https://uy-bozor.uz/uploads/images/4591698925230.jpg",
        "https://uy-bozor.uz/uploads/images/11001698925228.jpg",
        "https://uy-bozor.uz/uploads/images/14191699958269.jpg",
      ],
      nomi: "Ideal Jalyuzi dan ideal xizmatlar va takliflar!",
      price: 50220,
      shahar: "Jizzax",
      tuman: "So'x",
      manzil: "Yangi qurilgan uylar",
      xonalar: 5,
      yashashMaydon: 88,
      umumiyMaydon: 88,
      uchastkaMaydon: 6,
      joylashuvi: "Shaharda",
      qavati: 1,
      shiftBalandligi: 3,
      mebel: false,
      uyHolati: "O'rtacha",
      qurilishTuri: "G'ishtli",
      uyTuri: "Uy",
      suv: "Uyda",
      elektr: true,
      isitish: "Markazlashgan, gazda",
      gaz: "Maagistral",
      sanuzel: "Hovlida",
      yili: "2018",
      mavjudNarsalar: "Koditsioner, ErTo'la, omborcha",
      yaqinidaJoylashgan: "Bollar bog'chasi",
      vositachilik: false,
      holati: "Yangi",
      malumot:
        "Продается квартира в центре себзара квартира 1 этаж / 4 комнаты 4х этажный дом.в квартире доступно старые мебели , двери и тд. Есть всякое удобство. Не требует ремонта.Если вам не нравится вы можете с легкостью отремонтировать) в квартире не жили студенты!",
    },
    {
      id: 223252243,
      rasmlar: [
        "https://uy-bozor.uz/uploads/images/20021699958268.jpg",
        "	https://uy-bozor.uz/uploads/images/15241699958268.jpg",
        "https://uy-bozor.uz/uploads/images/9161699958268.jpg",
        "https://uy-bozor.uz/uploads/images/14191699958269.jpg",
      ],
      nomi: "Ideal Jalyuzi dan ideal xizmatlar va takliflar!",
      price: 90000,
      shahar: "Farg'ona",
      tuman: "Rishton",
      manzil: "Yangi qurilgan uylar",
      xonalar: 19,
      yashashMaydon: 88,
      umumiyMaydon: 88,
      uchastkaMaydon: 6,
      joylashuvi: "Shaharda",
      qavati: 1,
      shiftBalandligi: 3,
      mebel: false,
      uyHolati: "O'rtacha",
      qurilishTuri: "G'ishtli",
      uyTuri: "Uy",
      suv: "Uyda",
      elektr: true,
      isitish: "Markazlashgan, gazda",
      gaz: "Maagistral",
      sanuzel: "Hovlida",
      yili: "2018",
      mavjudNarsalar: "Koditsioner, ErTo'la, omborcha",
      yaqinidaJoylashgan: "Bollar bog'chasi",
      vositachilik: false,
      holati: "Yangi",
      malumot:
        "Продается квартира в центре себзара квартира 1 этаж / 4 комнаты 4х этажный дом.в квартире доступно старые мебели , двери и тд. Есть всякое удобство. Не требует ремонта.Если вам не нравится вы можете с легкостью отремонтировать) в квартире не жили студенты!",
    },
    {
      id: 259532543,
      rasmlar: [
        "https://uy-bozor.uz/uploads/images/20021699958268.jpg",
        "	https://uy-bozor.uz/uploads/images/15241699958268.jpg",
        "https://uy-bozor.uz/uploads/images/9161699958268.jpg",
        "https://uy-bozor.uz/uploads/images/14191699958269.jpg",
      ],
      nomi: "Ideal Jalyuzi dan ideal xizmatlar va takliflar!",
      price: 17000,
      shahar: "Marg'ilon",
      tuman: "Dang'ara",
      manzil: "Yangi qurilgan uylar",
      xonalar: 2,
      yashashMaydon: 88,
      umumiyMaydon: 88,
      uchastkaMaydon: 6,
      joylashuvi: "Shaharda",
      qavati: 1,
      shiftBalandligi: 3,
      mebel: false,
      uyHolati: "O'rtacha",
      qurilishTuri: "G'ishtli",
      uyTuri: "Uy",
      suv: "Uyda",
      elektr: true,
      isitish: "Markazlashgan, gazda",
      gaz: "Maagistral",
      sanuzel: "Hovlida",
      yili: "2018",
      mavjudNarsalar: "Koditsioner, ErTo'la, omborcha",
      yaqinidaJoylashgan: "Bollar bog'chasi",
      vositachilik: false,
      holati: "Yangi",
      malumot:
        "Продается квартира в центре себзара квартира 1 этаж / 4 комнаты 4х этажный дом.в квартире доступно старые мебели , двери и тд. Есть всякое удобство. Не требует ремонта.Если вам не нравится вы можете с легкостью отремонтировать) в квартире не жили студенты!",
    },
    {
      id: 49021001,
      rasmlar: [
        "https://uy-bozor.uz/uploads/images/20021699958268.jpg",
        "	https://uy-bozor.uz/uploads/images/15241699958268.jpg",
        "https://uy-bozor.uz/uploads/images/9161699958268.jpg",
        "https://uy-bozor.uz/uploads/images/14191699958269.jpg",
      ],
      nomi: "Ideal Jalyuzi dan ideal xizmatlar va takliflar!",
      price: 42000,
      shahar: "Namangan",
      tuman: "Oltiariq",
      manzil: "Yangi qurilgan uylar",
      xonalar: 7,
      yashashMaydon: 88,
      umumiyMaydon: 88,
      uchastkaMaydon: 6,
      joylashuvi: "Shaharda",
      qavati: 1,
      shiftBalandligi: 3,
      mebel: false,
      uyHolati: "O'rtacha",
      qurilishTuri: "G'ishtli",
      uyTuri: "Uy",
      suv: "Uyda",
      elektr: true,
      isitish: "Markazlashgan, gazda",
      gaz: "Maagistral",
      sanuzel: "Hovlida",
      yili: "2018",
      mavjudNarsalar: "Koditsioner, ErTo'la, omborcha",
      yaqinidaJoylashgan: "Bollar bog'chasi",
      vositachilik: false,
      holati: "Yangi",
      malumot:
        "Продается квартира в центре себзара квартира 1 этаж / 4 комнаты 4х этажный дом.в квартире доступно старые мебели , двери и тд. Есть всякое удобство. Не требует ремонта.Если вам не нравится вы можете с легкостью отремонтировать) в квартире не жили студенты!",
    },
    {
      id: 222342543,
      rasmlar: [
        "https://uy-bozor.uz/uploads/images/20021699958268.jpg",
        "	https://uy-bozor.uz/uploads/images/15241699958268.jpg",
        "https://uy-bozor.uz/uploads/images/9161699958268.jpg",
        "https://uy-bozor.uz/uploads/images/14191699958269.jpg",
      ],
      nomi: "Ideal Jalyuzi dan ideal xizmatlar va takliflar!",
      price: 68000,
      shahar: "Surxondaryo",
      tuman: "Quva",
      manzil: "Yangi qurilgan uylar",
      xonalar: 9,
      yashashMaydon: 88,
      umumiyMaydon: 88,
      uchastkaMaydon: 6,
      joylashuvi: "Shaharda",
      qavati: 1,
      shiftBalandligi: 3,
      mebel: false,
      uyHolati: "O'rtacha",
      qurilishTuri: "G'ishtli",
      uyTuri: "Uy",
      suv: "Uyda",
      elektr: true,
      isitish: "Markazlashgan, gazda",
      gaz: "Maagistral",
      sanuzel: "Hovlida",
      yili: "2018",
      mavjudNarsalar: "Koditsioner, ErTo'la, omborcha",
      yaqinidaJoylashgan: "Bollar bog'chasi",
      vositachilik: false,
      holati: "Yangi",
      malumot:
        "Продается квартира в центре себзара квартира 1 этаж / 4 комнаты 4х этажный дом.в квартире доступно старые мебели , двери и тд. Есть всякое удобство. Не требует ремонта.Если вам не нравится вы можете с легкостью отремонтировать) в квартире не жили студенты!",
    },
    {
      id: 222912543,
      rasmlar: [
        "https://uy-bozor.uz/uploads/images/20021699958268.jpg",
        "	https://uy-bozor.uz/uploads/images/15241699958268.jpg",
        "https://uy-bozor.uz/uploads/images/9161699958268.jpg",
        "https://uy-bozor.uz/uploads/images/14191699958269.jpg",
      ],
      nomi: "Ideal Jalyuzi dan ideal xizmatlar va takliflar!",
      price: 78000,
      shahar: "Sirdaryo",
      tuman: "Furqat",
      manzil: "Yangi qurilgan uylar",
      xonalar: 11,
      yashashMaydon: 88,
      umumiyMaydon: 88,
      uchastkaMaydon: 6,
      joylashuvi: "Shaharda",
      qavati: 1,
      shiftBalandligi: 3,
      mebel: false,
      uyHolati: "O'rtacha",
      qurilishTuri: "G'ishtli",
      uyTuri: "Uy",
      suv: "Uyda",
      elektr: true,
      isitish: "Markazlashgan, gazda",
      gaz: "Maagistral",
      sanuzel: "Hovlida",
      yili: "2018",
      mavjudNarsalar: "Koditsioner, ErTo'la, omborcha",
      yaqinidaJoylashgan: "Bollar bog'chasi",
      vositachilik: false,
      holati: "Yangi",
      malumot:
        "Продается квартира в центре себзара квартира 1 этаж / 4 комнаты 4х этажный дом.в квартире доступно старые мебели , двери и тд. Есть всякое удобство. Не требует ремонта.Если вам не нравится вы можете с легкостью отремонтировать) в квартире не жили студенты!",
    },
    {
      id: 222543,
      rasmlar: [
        "https://uy-bozor.uz/uploads/images/20021699958268.jpg",
        "	https://uy-bozor.uz/uploads/images/15241699958268.jpg",
        "https://uy-bozor.uz/uploads/images/9161699958268.jpg",
        "https://uy-bozor.uz/uploads/images/14191699958269.jpg",
      ],
      nomi: "Ideal Jalyuzi dan ideal xizmatlar va takliflar!",
      price: 12500,
      shahar: "Farg'ona",
      tuman: "Quva",
      manzil: "Yangi qurilgan uylar",
      xonalar: 1,
      yashashMaydon: 88,
      umumiyMaydon: 88,
      uchastkaMaydon: 6,
      joylashuvi: "Shaharda",
      qavati: 1,
      shiftBalandligi: 3,
      mebel: false,
      uyHolati: "O'rtacha",
      qurilishTuri: "G'ishtli",
      uyTuri: "Uy",
      suv: "Uyda",
      elektr: true,
      isitish: "Markazlashgan, gazda",
      gaz: "Maagistral",
      sanuzel: "Hovlida",
      yili: "2018",
      mavjudNarsalar: "Koditsioner, ErTo'la, omborcha",
      yaqinidaJoylashgan: "Bollar bog'chasi",
      vositachilik: false,
      holati: "Yangi",
      malumot:
        "Продается квартира в центре себзара квартира 1 этаж / 4 комнаты 4х этажный дом.в квартире доступно старые мебели , двери и тд. Есть всякое удобство. Не требует ремонта.Если вам не нравится вы можете с легкостью отремонтировать) в квартире не жили студенты!",
    },
  ],
  regions: [
    {
      id: 52432423,
      title: "Oltiariq",
    },
    {
      id: 932564,
      title: "Bag'dod",
    },
    {
      id: 6846087,
      title: "Beshariq",
    },
    {
      id: 6784890,
      title: "Buvayda",
    },
    {
      id: 375056750,
      title: "Dang'ara",
    },
    {
      id: 68746888,
      title: "Farg'ona",
    },
    {
      id: 68431322,
      title: "Furqat",
    },
    {
      id: 43468477,
      title: "Qo'shtepa",
    },
    {
      id: 6664444,
      title: "Quva",
    },
    {
      id: 68786645,
      title: "Rishton",
    },
    {
      id: 546557788,
      title: "So'x",
    },
  ],
  counties: [
    { id: 686767648, title: "Toshkent" },
    { id: 6464564, title: "Samarqand" },
    { id: 7878888, title: "Xorazm" },
    { id: 684644798, title: "Urganch" },
    { id: 64822888, title: "Andijon" },
    { id: 88978645, title: "Namangan" },
    { id: 67863215, title: "Buxoro" },
    { id: 6862020002, title: "Navoiy" },
    { id: 57856467, title: "Jizzax" },
    { id: 684682206, title: "Qo'qon" },
    { id: 788884401, title: "Farg'ona" },
    { id: 654674788, title: "Marg'ilon" },
    { id: 464133388, title: "Qashqadaryo" },
    { id: 13551446, title: "Surxondaryo" },
    { id: 6846320077, title: "Sirdaryo" },
  ],
};
